irohalab/mira-resource-indexer

src/main.ts
src/storage/pg-store.ts

fix: https://github.com/irohalab/indexer/issues/2

rename DBStore to PostgresStore

---

.dockerignore
Dockerfile
README.md
docker-compose.yml

add docker support

---

package.json

We can add CI service to test every PR.

add lint command

---

.github/workflows/checkin.yml
README.md

test PR: https://github.com/irohalab/indexer/pull/21

add github actions to test lint code

---

.github/workflows/checkin.yml
Dockerfile
docker-compose.yml

fix code coverage report generate

fix code coverage 

---

src/scraper/bangumi-moe.ts
src/scraper/dmhy.ts

After investigation. I found that the scrapper doesn't close the Page object properly. cause an memory issue.
beside that:
fix potential issue which may cause scrapper exception stop the whole application.

fix bug that cause dmhy scrapper leak memory

---

src/scraper/bangumi-moe.ts
src/scraper/dmhy.ts

fix potential issue which may cause scrapper exception stop the whole application.

Release v0.1.6

---

package.json
src/utils/sentry.ts
tsconfig.json

1. delete rootDir will change dist struct
2. copy package.json for require
ref: https://github.com/facebook/jest/blob/master/packages/jest-core/src/version.ts

fix tsconfig root

---

docker-compose.prod.yml
package.json
src/scraper/dmhy.ts

Reduce memory usage by block images and certain track script to be loaded.
fix:
add SENTRY_DSN env to docker-compose.prod.yml

Optimize puppeteer, reduce memory usage

---

README.md
docker-compose.yml
src/config.ts
src/storage/mongodb-store.spec.ts
src/storage/mongodb-store.ts
src/test/fake-config.ts
src/types.ts

fix: https://github.com/irohalab/mira-resource-indexer/issues/43 and https://github.com/irohalab/mira-resource-indexer/issues/42

fix sorted limited and case-insensitive

---

README.md
docker-compose.yml
src/config.ts
src/storage/mongodb-store.spec.ts
src/storage/mongodb-store.ts
src/test/fake-config.ts
src/types.ts

* fix sorted limited and case-insensitive
* fix search test result

fix sorted limited and case-insensitive (#51)

---

package.json

release v0.1.9

---

package.json

This is my miss to update version number, so we have to release next version.

update to v0.1.10

---

package.json
src/config.ts
src/main.ts
src/scraper/nyaa.ts
src/task/nyaa-task.ts
yarn.lock

ref: https://github.com/irohalab/mira-resource-indexer/issues/56

add nyaa scraper

---

README.md
docker-compose.prod.yml
package.json

0.2.0 add nyaa

---

README.md
docker-compose.prod.yml
package.json
src/config.ts
src/main.ts
src/scraper/nyaa.ts
src/task/nyaa-task.ts
yarn.lock

Release 0.2.0

---

README.md
docker-compose.prod.yml

1. update readme
2. start node with process name

start node with process name

---

package.json
src/scraper/abstract/base-scraper.ts

The current logic is wrong which cause the scrapper unable to store detail page

a quick fix for scrapper logic fault

---

package.json
src/scraper/abstract/base-scraper.ts

* a quick fix for scrapper logic fault

a quick fix for scrapper logic fault (#70)

---

package.json
src/scraper/abstract/base-scraper.ts
src/scraper/bangumi-moe.ts
src/scraper/dmhy.ts
src/scraper/nyaa.ts

* fix the report name is incorrect for each scraper.
update version
* fix some error cause sub task failed to retry

0.3.2 (#72)

---

package.json
src/scraper/dmhy.ts

* print the body of response when the error happened
* update version, fix bug

Test body (#74)

---

package.json
src/scraper/dmhy.ts

DMHY changed their DOM structure cause our scraper to fail to scrape

fix bug caused by dmhy change it's dom structure

---

package.json
src/main.ts
src/rest-api/items-query.ts
src/scraper/abstract/base-scraper.ts
src/scraper/bangumi-moe.ts
src/scraper/dmhy.ts
src/scraper/nyaa.ts
src/service/database-service.ts
src/storage/mongodb-item-store.spec.ts
src/storage/mongodb-item-store.ts
src/storage/mongodb-task-store.spec.ts
src/storage/mongodb-task-store.ts
src/task/task-orchestra.spec.ts
src/task/task-orchestra.ts
src/task/task-status.ts
src/test/fake-scraper.ts
src/test/in-memory-item-store.ts
src/test/in-memory-task-store.ts
src/types.ts

* add task store, change interface name and definition for PersistentStorage
* fix style issue
* change task-orchestra logic
* update task orchestra logic and other dependencies.
* update test case, fix some bugs
* fix bugs wit mongodb-task-store
* change retry count manipulate position
* update version
* fix style issue
* force queue a CommonTask if the last main task execution time elapse more than checkInterval
* fix code style issue

Persistent task management (#78)

---

package.json
src/service/database-service.ts

* fix code style issue
* update version
Co-authored-by: lordfriend <lordfriend@outlook.com>

Remove unused code (#80)

---

src/scraper/dmhy.ts

1. for example https://share.dmhy.org/topics/view/544161_Sword_Art_Online_-_Alicization_War_of_Underworld_13_HEVC-10Bit-2160P_AAC_GB_BIG5_WEB-Rip_MKV_ass.html
If page been deleted, we need return 404 code.

fix dmhy 404 page

---

.gitignore
package.json
src/scraper/nyaa.ts
src/service/database-service.ts
src/storage/mongodb-item-store.ts
src/storage/mongodb-task-store.spec.ts
src/storage/mongodb-task-store.ts
src/task/main-task.ts
src/task/sub-task.ts
src/task/task-orchestra.ts
src/task/task-types.ts
src/utils/azure-logger.ts
src/utils/sentry.ts
yarn.lock

Add an Azure logger that can send custom logs into Azure Log Analytics to do further analysis without worry exceed Sentry monthly quota.
Fix the task queue logic that will re-queue the task which considers equal. No duplication is in the task queue or failed task queue.
The following is considered equal:
- CommonTask which type is MainTask.
- MainTask which has the same pageNo.
- SubTask which has the same uri.

Add Azure Logger and Fix task duplication issue

---

docker-compose.prod.yml
docker-compose.yml
package.json
src/scraper/nyaa.ts

- update ENV in docker-compose file
- update nyaa in order to capture error for azure logger and ignore some erros like 404 or timeout for sentry

0.5.0 update

---

docker-compose.prod.yml
docker-compose.yml

add docker config

---

package.json

release v0.5.1

---

package.json
src/main.ts
src/scraper/bangumi-moe.ts
src/scraper/dmhy.ts
src/scraper/nyaa.ts
src/server.ts
src/service/database-service.ts
src/storage/mongodb-task-store.ts
src/task/task-orchestra.ts
src/utils/logger-factory.ts
yarn.lock

replace all console.log with winston to better format the log output

Logs elastic

---

README.md
docker-compose.prod.yml
package.json

- update docker-compose.prod.yml, readme.
- bump version to 0.6.0
- complete #133

Add deployment for acg_rip mode

---

.github/workflows/release.yml
README.md
docker-compose.prod.yml
package.json
src/config.ts
src/main.ts
src/scraper/acg-rip.ts
src/scraper/dmhy.ts
src/utils/torrent-utils.ts
yarn.lock

- Add acg.rip support #132 
- Add deployment of acg.rip #134 
- update some dependencies

release 0.6.0

---

docker-compose.prod.yml
src/config.ts
src/main.ts
src/scraper/mikanani-me.ts
src/utils/normalize.ts

mikanani.me:
- Team and publisher are the same concept.
- has magnet uri and torrent URL provided, torrent URL can be unreachable. in this case, the files will be null
- New env mode=mikanani

add mikanani-me scraper to scrap mikanani.me.
